### ISSUE TITLE
Objective #3 and #4, HALP

### ISSUE THREAD

**Issue by Axelm3sh** [syeaw0/CS1C---Class-Project-Warehouse#22]
So basically started the skeleton output prototype on my end for Total purchases by all members Report (#3) and found it was very similar to PrintMemberPurchaseReport(). 
The catch is that I needed to _print all the member's purchases under the category of an ID number_ (see sample output) for all members then _total the purchases._ I think it's straight forward but a majority of the code is already in PrintMemberPurchaseReport, is it better to copy that and reuse it? It would keep in style with some other reports but IDK how to feel about reusing someone's hard worked code lol. 

The other thing is with (#4), I have to output a searched item and in total how much was sold and its total price. Isn't that handled already by a method in Inventory? Maybe I just need to implement an output for that search function, so this could already be a simple _get info from object and display it_

Discuss plz

**Comment by Axelm3sh** [comment]
Still trying to _refine_ this, it is working, but will keep this open till fully resolved.

**Comment by mciver24** [comment]
i have most of the output stuff done, it just needs to be refined i can show you the stuff i have after class today

**Comment by armanJafa** [comment]
Oh hey their little issue. Guess whats going to happen? Thats right. You're about to GET REEEEEKKKKTTTT SON. 

CLOSED MOTHER FUCKER
