### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by mciver24** [syeaw0/CS1C---Class-Project-Warehouse#32]
Alright i created a prototype repository that has a working prototype for the project.
I could not get it to work with the dates, and when the lists are created there is a copy of one node however it seems like everything else works. The output is perfect, but i figured we could show it at the checkpoint on tuesday.

-only tested with first day
- changed a lot of stuff so i wanted to see what you guys thought and make sure it worked with you guys and not just me

**Comment by mciver24** [comment]
*output isn't perfect haha

**Comment by Axelm3sh** [comment]
It works, need refinement
