### ISSUE TITLE
Need Error Checking

### ISSUE THREAD

**Issue by Axelm3sh** [syeaw0/CS1C---Class-Project-Warehouse#37]
> -Check for empty string in PrintItemSalesTotal  
> -Searching ID for member

**Comment by mciver24** [comment]
program no longer crashes ;)

**Comment by armanJafa** [comment]
What does this issue and a door have in common?

THEY BOTH JUST GOT CLOSED MOTHER FUCKER OWW

**Comment by armanJafa** [comment]
What does this issue and a door have in common?

THEY BOTH JUST GOT CLOSED MOTHER FUCKER OWW
