### ISSUE TITLE
Regarding reading in the Date. 

### ISSUE THREAD

**Issue by armanJafa** [syeaw0/CS1C---Class-Project-Warehouse#40]
I feel that in order to read in the date correctly, we need to change how we are doing it. Right now out date class reads in the date as a character array and uses atoi to store into the date. I think this might be the wrong way of going about it. At the very least, we should try out reading in the data simply as an integer and ignoring the slashes in between. It may or may not work but i think that we should try it this way to see if it will work. 
- I tried getting this to work but my eclipse is acting up on me. We can discuss this in class. 

CHA

**Comment by Axelm3sh** [comment]
FIXED! SOLVED FROM SAMS AWESOMESAUCENESS. REVEALATIPONDASL;DFJSDLKGJS
