### ISSUE TITLE
Item list Merging lists from mutliple files

### ISSUE THREAD

**Issue by Axelm3sh** [syeaw0/CS1C---Class-Project-Warehouse#42]
Created Lists from different text files must be somehow merged. 

Also Adding or deleting Members should fix the lists to point to the correct things.

**Comment by mciver24** [comment]
alright got this working i will update this later

**Comment by armanJafa** [comment]
What the difference between me and you? 

I'm handsome
I'm smarter
and
I'M NOT CLOSED DOWN MOTHER FUCKER
