### ISSUE TITLE
Requirements 9-12 needed(?)

### ISSUE THREAD

**Issue by Axelm3sh** [syeaw0/CS1C---Class-Project-Warehouse#43]
Rushhour

**Comment by Axelm3sh** [comment]
Jacob needed 12
Sam > 9
Arman > 10
Dan > 11

**Comment by armanJafa** [comment]
Hey HEEEYYYY. GUESS WHATT. YOU JUST CLOSED SON 

AWOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by armanJafa** [comment]
Hey HEEEYYYY. GUESS WHATT. YOU JUST CLOSED SON

AWOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
