### ISSUE TITLE
Need to implement methods for Items. 

### ISSUE THREAD

**Issue by Axelm3sh** [syeaw0/CS1C---Class-Project-Warehouse#6]
Specifically, the pointers and how I can get them to work. Someone look at that shiz

**Comment by syeaw0** [comment]
Hey Daniel, I looked over your Item class and it seems fine to me. All you needed was a next pointer attribute and two methods to handle it (Set and Get), which you have. It is the inventory class that manages it as a list.

**Comment by syeaw0** [comment]
And thank you for managing the code and text files

**Comment by Axelm3sh** [comment]
fixed and implemented
